"use strict"

import { utils, fileHandler } from 'librext-core'
import cssHandler from '../css-handler.js'

let scope = 'global'
const defaultLocalScope = '.librext *'
let customLocalScope = '.placeholder *'

const buildBase = (uiSpec, outputDir, config) => {
    // console.log('[LibRext CSS - BaseBuilder] uiSpec', uiSpec);
    const title = `[ ${config.projectName} ] ` + 'BASE CSS STYLES'
    const subtitle = 'generated by LibRext'
    const headerComment = utils.codeComment(title, subtitle, 'css', 2)

    let varsSelector = ':root'
    if (scope == 'local') {
        varsSelector = defaultLocalScope
    } else if (scope == 'custom') {
        varsSelector = customLocalScope
    }
    const styleVars = []

    /* ================================================
     * Size Scale
     * --------------------------------------------- */

    uiSpec.sizes.forEach((sizeNum, idx) => {
        const scaleVar = {
            property: `${config.tokenPrefix}-scale-${idx + 1}`,
            value: `${sizeNum}px`,
        }
        styleVars.push(scaleVar);
    })

    /* ================================================
     * Space Scale
     * --------------------------------------------- */

    uiSpec.space.forEach((spaceNum, idx) => {
        const scaleVar = {
            property: `${config.tokenPrefix}-space-${idx + 1}`,
            value: `${spaceNum}px`,
        }
        styleVars.push(scaleVar);
    })

    /* ================================================
     * Text Formatting
     * --------------------------------------------- */

    const variablesContent = cssHandler.writeCssVarRule(varsSelector, styleVars);

    const prefaceContent = headerComment + '\n'
    let allContent = prefaceContent
    const parts = [
        { title: 'CSS Variables', subtitle: '', content: variablesContent },
    ]
    parts.forEach(part => {
        const partHeading = utils.codeComment(part.title, part.subtitle, 'css')
        allContent += partHeading + part.content + '\n'
    })

    /* ================================================
     * Output
     * --------------------------------------------- */

    fileHandler.writeFile(`${outputDir}/css/${config.filenamePrefix}-base.css`, allContent)
}

// module.exports = { build: buildBase };
export default buildBase