"use strict"

import { utils, fileHandler } from 'librext-core'
import cssHandler from '../css-handler.js'

let scope = 'global'
const defaultLocalScope = '.librext *'
let customLocalScope = '.placeholder *'

const buildShapes = (uiSpec, outputDir, config) => {
    // console.log('[LibRext CSS - ShapesBuilder] uiSpec', uiSpec);
    const title = `[ ${config.projectName} ] ` + 'SHAPE STYLES'
    const subtitle = 'generated by LibRext'
    const headerComment = utils.codeComment(title, subtitle, 'css', 2)

    let varsSelector = ':root'
    if (scope == 'local') {
        varsSelector = defaultLocalScope
    } else if (scope == 'custom') {
        varsSelector = customLocalScope
    }

    const styleVars = []
    const cRadiusPrefixes = [
        'none',
        'xs',
        'sm',
        'md',
        'lg',
        'xl',
    ]

    let prefaceContent = headerComment + '\n'
    let shapesContent = ''

    /* ================================================
     * Border Radii
     * --------------------------------------------- */

    uiSpec.radii.forEach((radVal, idx) => {
        const cPrefix = cRadiusPrefixes[idx]
        const cRadiusEntry = {
            property: `${config.tokenPrefix}-bradius-${cPrefix}`,
            value: radVal,
        }
        styleVars.push(cRadiusEntry);
        const selector = `.${config.tokenPrefix}-bradius.${cPrefix}`
        const props = [
            {
                property: 'border-radius',
                value: radVal,
            },
        ]
        shapesContent += cssHandler.writeCssRule(selector, props)
    })

    /* ================================================
     * Box Shadows
     * --------------------------------------------- */

    for (const [shadowSize, shadowVal] of Object.entries(uiSpec.shadows)) {
        const sRadiusEntry = {
            property: `${config.tokenPrefix}-bshadow-${shadowSize}`,
            value: shadowVal,
        }
        styleVars.push(sRadiusEntry);
        const selector = `.${config.tokenPrefix}-bshadow.${shadowSize}`
        const props = [
            {
                property: 'box-shadow',
                value: shadowVal,
            },
        ]
        shapesContent += cssHandler.writeCssRule(selector, props)
    }

    /* ================================================
     * Widget Heights
     * --------------------------------------------- */

    for (const [widgetHtKey, widgetHtVars] of Object.entries(uiSpec.widgetHeights)) {
        const heightEntry = {
            property: `${config.tokenPrefix}-widget-${widgetHtKey}`,
            value: widgetHtVars.height,
        }
        styleVars.push(heightEntry);

        const selector = `.${config.tokenPrefix}-widget.${widgetHtKey}`
        const props = [
            {
                property: 'height',
                value: widgetHtVars.height,
            },
        ]
        shapesContent += cssHandler.writeCssRule(selector, props)
    }
    const variablesContent = cssHandler.writeCssVarRule(varsSelector, styleVars);

    /* ================================================
     * Cards
     * --------------------------------------------- */

    for (const [cardType, cardData] of Object.entries(uiSpec.cards)) {
        const selector = `.${config.tokenPrefix}-card.${cardType}`
        const props = [
            {
                property: 'height',
                value: `${uiSpec.sizes[cardData.height]}px`,
            },
            {
                property: 'border-radius',
                value: uiSpec.radii[cardData.borderRadius],
            },
            {
                property: 'padding',
                value: `${uiSpec.space[cardData.padding]}px`,
            },
            {
                property: 'box-shadow',
                value: uiSpec.shadows[cardData.boxShadow],
            },
        ]
        shapesContent += cssHandler.writeCssRule(selector, props)

        if (cardType == 'md') {
            shapesContent += cssHandler.writeCssRule(`.${config.tokenPrefix}-card`, props)
        }
    }

    /* ================================================
     * Text Formatting
     * --------------------------------------------- */

    // const prefaceContent = headerComment + '\n'
    let allContent = prefaceContent
    const parts = [
        { title: 'CSS Variables', subtitle: '', content: variablesContent },
        { title: 'Shapes', subtitle: '', content: shapesContent },
    ]
    parts.forEach(part => {
        const partHeading = utils.codeComment(part.title, part.subtitle, 'css')
        allContent += partHeading + part.content + '\n'
    })

    /* ================================================
     * Output
     * --------------------------------------------- */

    fileHandler.writeFile(`${outputDir}/css/${config.filenamePrefix}-shapes.css`, allContent)
}

// module.exports = { build: buildShapes };
export default buildShapes