"use strict"

import { utils, fileHandler } from 'librext-core'
import cssHandler from '../css-handler.js'

const buildText = (uiSpec, outputDir, config) => {
    // console.log('[LibRext CSS - TextBuilder] uiSpec', uiSpec);
    const title = 'TEXT STYLES'
    const subtitle = 'generated by LibRext'
    const headerComment = utils.codeComment(title, subtitle, 'css', 2)

    let prefaceContent = headerComment + '\n'

    const rootCssVars = []
    let rootCssVarContent = ''
    let fontFamContent = ''
    let fontScaleContent = ''
    let docRolesContent = ''

    /* ================================================
     * Font Family
     * --------------------------------------------- */

    for (const fontRole in uiSpec.fonts) {
        const currentFontFamily = uiSpec.fonts[fontRole]
        rootCssVars.push({
            property: `${config.tokenPrefix}-fontfam-${fontRole}`,
            value: currentFontFamily,
        })
        const fontRoleVars = [
            { property: 'font-family', value: currentFontFamily, },
        ]
        const fontRoleRule = cssHandler.writeCssRule(`.${config.tokenPrefix}-fontfam-${fontRole}`, fontRoleVars);
        fontFamContent += fontRoleRule + '\n'
    }

    /* ================================================
     * Typescale (by index)
     * --------------------------------------------- */

    uiSpec.fontSizes.forEach((fontSizeVal, idx) => {
        rootCssVars.push({
            property: `${config.tokenPrefix}-tscale-${idx + 1}`,
            value: fontSizeVal,
        })
        const fontSizeVars = [
            { property: 'font-size', value: fontSizeVal, },
        ]
        const fontSizeRule = cssHandler.writeCssRule(`.${config.tokenPrefix}-tscale-${idx + 1}`, fontSizeVars);
        fontScaleContent += fontSizeRule + '\n'
    })

    /* ================================================
     * Typescale (by name)
     * --------------------------------------------- */

    for (const fontSizeRole in uiSpec.libRextData.fontSizes) {
        rootCssVars.push({
            property: `${config.tokenPrefix}-tscale-${fontSizeRole}`,
            value: uiSpec.libRextData.fontSizes[fontSizeRole],
        })
        const fontSizeVars = [
            { property: 'font-size', value: uiSpec.libRextData.fontSizes[fontSizeRole], },
        ]
        const fontSizeRule = cssHandler.writeCssRule(`.${config.tokenPrefix}-tscale-${fontSizeRole}`, fontSizeVars);
        fontScaleContent += fontSizeRule + '\n'
    }

    /* ================================================
     * Document Roles
     * --------------------------------------------- */

    docRolesContent += utils.codeComment('DOCUMENT ROLES', '')

    for (const docRoleName in uiSpec.docRoles) {
        const currentDocRole = uiSpec.docRoles[docRoleName]
        const docRoleData = uiSpec.libRextData.docRoles[docRoleName]
        // console.log('[LibRext CSS - TextBuilder] currentDocRole', currentDocRole)
        // console.log('[LibRext CSS - TextBuilder] docRoleData', docRoleData)

        let weightType = currentDocRole.weight
        if (currentDocRole.weight == 'regular') {
            weightType = 'normal'
        }
        const sizeVal = `var(--${config.tokenPrefix}-tscale-${docRoleData.typescale})`

        const fontFamVal = `var(--${config.tokenPrefix}-fontfam-${currentDocRole.fontFamily})`
        const isItalic = docRoleData.styles.includes('italic')
        const fontStyleVal = isItalic ? 'italic' : 'normal'
        const weightVal = uiSpec.fontWeights[weightType]
        const letterSpacingVal = uiSpec.letterSpacings[currentDocRole.letterSpacing];
        const lineHeightVal = uiSpec.lineHeights[currentDocRole.lineHeight];
        const marginPreset = uiSpec.marginPresets[currentDocRole.lineHeight];
        const textColourRole = uiSpec.docRoleColours[docRoleName];
        const textColour = uiSpec.colors[textColourRole]

        const docRoleVars = [
            { property: 'font-weight', value: weightVal, },
            { property: 'font-size', value: sizeVal, },
            { property: 'font-family', value: fontFamVal, },
            { property: 'font-style', value: fontStyleVal, },
            { property: 'letter-spacing', value: letterSpacingVal },
            { property: 'line-height', value: lineHeightVal },
            { property: 'margin-top', value: marginPreset.marginTop },
            { property: 'margin-bottom', value: marginPreset.marginBottom },
            { property: 'color', value: textColour },
        ]

        const selectorHtml = docRoleData.html.length == 0 ? '' : `${docRoleData.html},\n`
        let docRoleSelector = `${selectorHtml}.${docRoleData.class}`

        const docRoleRule = cssHandler.writeCssRule(docRoleSelector, docRoleVars);
        const docRoleComment = utils.codeComment(docRoleName, `typescale size = ${docRoleData.typescale}`)

        docRolesContent += docRoleComment + docRoleRule + '\n'
    }

    /* ================================================
     * Text Formatting
     * --------------------------------------------- */

    let allContent = prefaceContent
    const rootCssVarRule = cssHandler.writeCssVarRule(cssHandler.ROOT_SELECTOR, rootCssVars);
    rootCssVarContent = rootCssVarContent + rootCssVarRule + '\n'
    const parts = [
        { title: 'CSS Variables', subtitle: '', content: rootCssVarContent },
        { title: 'Font Families', subtitle: '', content: fontFamContent },
        { title: 'Font Scale', subtitle: '', content: fontScaleContent },
        { title: 'Document Roles', subtitle: '', content: docRolesContent },
    ]
    parts.forEach(part => {
        const partHeading = utils.codeComment(part.title, part.subtitle, 'css')
        allContent += partHeading + part.content + '\n'
    })

    /* ================================================
     * Output
     * --------------------------------------------- */

    fileHandler.writeFile(`${outputDir}/css/${config.filenamePrefix}-text.css`, allContent)
}

// module.exports = { build: buildText };
export default buildText